http_server:
  listen: :8000
  read_timeout: 15s
  write_timeout: 15s

databases:
  postgres:
    conn_config:
      network: tcp
      database: ${POSTGRES_DB}
      host: ${POSTGRES_HOST}
      port: 5432
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    max_open_conns: 0
    max_idle_conns: 2
    conn_max_idle_time: 0s

graceful_timeout: 20s

bot:
  token: ${TOKEN} 

google_sheets:
  credentials_file: "./config/dev/google-sheets-service-account-key.json" # TODO: change this later 
  spreadsheet_id: ${GOOGLE_SPREADSHEET_ID}
  sheet_name: "Main"

